[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[alist]
source = "github"
github = "Xhofe/alist"
use_max_tag = true
prefix = "v"

[astrofox]
source = "github"
github = "astrofox-io/astrofox"
use_max_tag = true
prefix = "v"

[bark-server]
source = "github"
github = "Finb/bark-server"
use_max_tag = true
prefix = "v"

[bookxnote]
source = 'regex'
regex = "http://www.bookxnote.com/setup/BookxNotePro_ubuntu_amd64-([\\d.]+).deb"
url = "http://www.bookxnote.com/"

[citespace]
source = "regex"
regex = "([\\d.A-Z]+) Basic"
url = "https://citespace.podia.com/download"

[clash4windows]
source = "github"
github = "Fndroid/clash_for_windows_pkg"
use_max_tag = true
prefix = "v"


[dendrite]
source = "github"
github = "matrix-org/dendrite"
use_max_tag = true


[dida]
source = "cmd"
cmd = '''
_url=https://dida365.com/static/getApp/download\?type\=linux_deb_x64
curl -sSL -D - $_url -o /dev/null |
 grep -oE 'dida-[0-9.]+-amd64.deb' |
 cut -d'-' -f2
'''

[dingtalk]
source = "regex"
url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/xc_dingtalk_update/linux_deb/Update/other/amd64/linux_dingtalk_update_package_gray.json"
regex = '"update_version": "([\d\w.-]+)"'

[fbreader]
source = 'cmd'
cmd = '''json=$(curl -H 'X-Ubuntu-Series: 16' https://api.snapcraft.io/api/v1/snaps/details/fbreader)
ver=$(echo $json | jq -r '.version')
revision=$(echo $json | jq -r '.revision')
echo $ver-$revision
'''

[foxit-pdfeditor]
source = "regex"
regex = "([\\d.]+)[\\\\a-z0-9]+V10 SP1"
url = "https://www.foxitsoftware.cn/portal/download/getpackage.html?product=Foxit-PhantomPDF-Linux&language=English&platform=Linux&version=&package_type=&special=0&oldVersion=null"

[gstarcad]
source = "regex"
regex = "https://hccad.gstarcad.cn/linux[\\d]+/v([\\d.]+)/deb/gstarcad_[\\d.]+_amd64.deb"
url = "https://www.gstarcad.com/cad_linux/"

[iauto]
source = "cmd"
cmd = '''
_url='https://www.iautodraw.com'
_jspath=$(curl ${_url} | grep -oE 'app.([a-z0-9]+).js')
curl ${_url}/static/js/${_jspath} |
    grep -oE 'IAuto Setup [0-9.]+\(win 32\).exe' |
    grep -oE '[0-9.]+' |
    head -1
'''

[icalingua-plus-plus]
source = "github"
github = "Icalingua-plus-plus/Icalingua-plus-plus"
use_latest_release = true

[lsky-pro]
source = "github"
github = "lsky-org/lsky-pro"
use_max_tag = true

[lx-music]
source = "github"
github = "lyswhut/lx-music-desktop"
use_max_tag = true
prefix = "v"

[mautrix-whatsapp]
source = "github"
github = "mautrix/whatsapp"
use_max_tag = true
prefix = "v"

[mathpix-snipping-tool]
source = "regex"
regex = "https://download.mathpix.com/linux/Mathpix_Snipping_Tool-x86_64.v([\\d.]+).AppImage"
url = "https://mathpix.com/"

[mpreal]
source = "github"
github = "advanpix/mpreal"
use_max_tag = true
include_regex = "mpfrc.*"

[mtxx]
source = "regex"
regex = "xiuxiu.dl.meitu.com/mtxx-x86_64-([\\d.]+).deb"
url = "https://pc.meitu.com/download"


[ox-console]
source = "regex"
regex = ""
url = "https://www.doornik.com/products.html#OxCons"

[qqmusic]
source = "regex"
regex = "https://dldir1.qq.com/music/clntupate/linux/deb/qqmusic_([\\d.]+)_amd64.deb"
url = "https://y.qq.com/download/download.html"

[rustdesk-server]
source = "github"
github = "rustdesk/rustdesk-server"
use_latest_release = true


[ryusak]
source = "github"
github = "Ecks1337/RyuSAK"
use_max_tag = true
prefix = "v"

[stanc]
source = "github"
github = "stan-dev/cmdstan"
use_max_tag = true

[stanmath]
source = "github"
github = "stan-dev/math"
use_max_tag = true

[svstudio]
source = "regex"
regex = "svstudio/([\\d.]+)"
url = "https://auth.dreamtonics.com/update.php?operation=fetch-update&product=Synthesizer%20V%20Studio%20Basic&key&current-version=67073&platform=linux"

[typora]
source = "cmd"
cmd = '''
curl -s https://www.typora.io/linux/Packages | grep Version | cut -f 2 -d ' ' |  cut -f 1 -d '-' | uniq|tail -1
'''

[yade]
source = "gitlab"
gitlab = "yade-dev/trunk"
use_max_tag = true

[yank-note]
source = "github"
github = "purocean/yn"
use_max_tag = true
prefix = "v"

[wiznote]
source = "regex"
regex = "([0-9.]+)\\s?\\(\\d{4}-\\d+-\\d\\)"
url = "https://www.wiz.cn/zh-cn/wiznew.html"

[zwcad]
source = "regex"
regex = "https://dl.zwsoft.cn/zwcad/cad_linux/[\\d]+/[\\w\\d]+/zwcad([\\d_.]+)_amd64.deb"
url = "https://www.zwsoft.cn/product/zwcad/linux"
